# Generated by Django 3.2 on 2022-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
