# Generated by Django 3.2 on 2022-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='users',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
